trigger:
- main  # Change this if you're using a different branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2    # Only for .NET, remove if you're using something else
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: echo "Building Storynaps App..."
  displayName: 'Build App'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.SourcesDirectory)'
    artifactName: 'drop'
