apiVersion: apps/v1
kind: Deployment
metadata:
  name: storynaps-Deployment
  labels:
    app: storynaps
spec:
  replicas: 3
  selector:
  matchLabels:
    app: storynaps
  template:
    metadata:
      labels:
        app: storynaps
    spec:
      containers:
      - name: storynaps-container
        image: storynaps:v1
        ports:
          - containerPort: 80
        resources:
         requests:
          memory: "128Mi"
          cpu: "100m"
         limits:
          memory: "256Mi"
          cpu: "200m"  